---
- hosts: myBastion
  become: true
  tasks:

  - name: "rhel9-prep : TEMPLATE /etc/motd (complete)"
    template:
      src: motd-complete.j2
      dest: /etc/motd
      owner: root
      group: root
      mode: 0644  

